/**
 * Arabic only. Every BubblesCarWash technician reads Arabic, and a language
 * toggle in a tool used one-handed beside a car is a setting nobody wants.
 */
export const copy = {
  brand: 'BubblesCarWash',
  role: 'تطبيق الفنّي',

  signInTitle: 'سجّل دخولك',
  signInSub: 'برقم الجوال المسجّل لدى الإدارة.',
  phonePlaceholder: '5X XXX XXXX',
  sendCode: 'إرسال الرمز',
  sending: 'جارٍ الإرسال…',
  codeSentTo: 'أرسلنا الرمز إلى',
  verify: 'دخول',
  verifying: 'جارٍ التحقق…',
  changeNumber: 'تغيير الرقم',

  today: 'مهامك',
  noJobs: 'لا مهام الآن.',
  noJobsSub: 'ستظهر هنا فور إسنادها إليك.',
  history: 'المنجزة',
  notifications: 'التنبيهات',
  noTeam: 'غير مرتبط بفريق',
  claimedByYou: 'مستلمة باسمك',
  availableToTeam: 'متاحة لأعضاء الفريق',
  noHistory: 'لم تُنجز مهام بعد.',
  signOut: 'تسجيل الخروج',
  teamJob: 'مهمة متاحة لفريقك',
  teamJobSub: 'الحجز أُسند للفريق تلقائيًا. استلمه قبل بدء التوجه حتى يعرف بقية الفريق أنه معك.',
  claimJob: 'استلام المهمة',
  claimed: 'أصبحت المهمة باسمك',
  unavailableJob: 'لم تعد هذه المهمة متاحة. ربما استلمها عضو آخر من الفريق.',
  backToJobs: 'العودة للمهام',
  customer: 'العميل',
  callCustomer: 'اتصال بالعميل',

  vehicle: 'السيارة',
  address: 'الموقع',
  accessNotes: 'ملاحظات الوصول',
  extras: 'إضافات',
  noExtras: 'لا إضافات',

  stages: {
    booked: 'لم يبدأ',
    arrived: 'وصلت',
    washed: 'اكتمل الغسيل',
    verified: 'تم التأكد',
  } as Record<string, string>,

  actions: {
    arrived: 'وصلت الموقع',
    washed: 'انتهيت من الغسيل',
    verified: 'تأكدت من الجودة',
  } as Record<string, string>,

  done: 'اكتملت المهمة',
  working: 'جارٍ الحفظ…',
  beforeEvidence: 'توثيق قبل الغسيل',
  afterEvidence: 'توثيق بعد الغسيل',
  evidenceInstruction: 'أضف صورًا واضحة من الجهات المطلوبة أو فيديو 360° كاملًا قبل الانتقال للمرحلة التالية.',
  takePhotos: 'التقاط صور',
  record360: 'تسجيل فيديو 360°',
  uploadingEvidence: 'جارٍ رفع التوثيق…',
  evidenceSaved: 'تم حفظ التوثيق بأمان',
  evidenceCount: (before: number, after: number) => `قبل الغسيل: ${before} · بعد الغسيل: ${after}`,
  cameraDenied: 'فعّل إذن الكاميرا لتوثيق السيارة.',
  reportProblem: 'بلاغ تشغيلي',
  openReport: 'إبلاغ الإدارة',
  accessProblem: 'تعذّر الوصول',
  otherProblem: 'مشكلة أخرى',
  problemDetails: 'التفاصيل',
  problemPlaceholder: 'اكتب ما حدث بوضوح',
  sendReport: 'إرسال البلاغ',
  incidentSent: 'وصل البلاغ إلى مركز التشغيل',
  cancel: 'إلغاء',

  services: { exterior: 'غسلة خارجية', full: 'غسلة كاملة' } as Record<string, string>,
  addOns: { wax: 'واكس حماية', tires: 'لمعة إطارات' } as Record<string, string>,
  sizes: { sedan: 'سيدان', suv: 'دفع رباعي', pickup: 'ونيت' } as Record<string, string>,

  errors: {
    wrongCode: 'الرمز غير صحيح أو انتهت صلاحيته.',
    tooManyRequests: 'محاولات كثيرة. انتظر دقيقة.',
    invalidPhone: 'رقم الجوال غير صحيح.',
    notATechnician: 'هذا الحساب ليس حساب فنّي. راجع الإدارة.',
    skippedStage: 'أكمل المرحلة السابقة أولًا.',
    alreadyPast: 'سُجّلت هذه المرحلة من قبل.',
    cancelled: 'أُلغي هذا الحجز.',
    notFound: 'المهمة غير موجودة.',
    beforeMediaRequired: 'أضف صورًا أو فيديو قبل الغسيل أولًا.',
    afterMediaRequired: 'أضف صورًا أو فيديو بعد الغسيل أولًا.',
    mediaWrongStage: 'هذا التوثيق لا يخص المرحلة الحالية.',
    badMediaType: 'نوع الملف غير مدعوم. استخدم صورة أو فيديو.',
    badMediaSize: 'الملف أكبر من الحد المسموح أو غير مكتمل.',
    storageUnavailable: 'التخزين غير متاح الآن. حاول لاحقًا.',
    jobClaimed: 'استلم سائق آخر هذه المهمة.',
    technicianNotInTeam: 'حسابك غير مرتبط بهذا الفريق.',
    outsideDriverShift: 'موعد المهمة خارج مناوبتك.',
    technicianBusy: 'لديك مهمة أخرى في الوقت نفسه.',
    badIncidentCategory: 'نوع البلاغ غير صحيح.',
    incidentNoteRequired: 'اكتب تفاصيل البلاغ.',
    offline: 'لا يوجد اتصال. تحقق من الشبكة.',
    unknown: 'تعذّر إكمال العملية.',
  } as Record<string, string>,
};
